version: '3'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: Your_password123
      ACCEPT_EULA: Y
    volumes:
      - ./data:/var/opt/mssql/data
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -h-1 -V1 -U sa -P $$SA_PASSWORD -Q \"DB_ID(['Weather'])\"" ]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 20s
    networks:
      - back

  backend:
    image: jrodrigv/webapi:latest
    environment:
      ASPNETCORE_URLS: http://+:5000
    depends_on:
      - db
    networks:
      - front
      - back

  frontend:
    image: jrodrigv/webapp:latest
    depends_on:
      - backend
    networks:
      - loadbalancer
      - front

  frontend2:
    image: jrodrigv/webapp:latest
    depends_on:
      - backend
    networks:
      - loadbalancer
      - front

  backend2:
    image: jrodrigv/webapi:latest
    environment:
      ASPNETCORE_URLS: http://+:5000
    depends_on:
      - db
    networks:
      - front
      - back

  loadbalancer:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - frontend2
    networks:
      - loadbalancer

networks:
  loadbalancer:
  front:
  back: